### ISSUE TITLE
pytokio -- import on python3 fails

### ISSUE THREAD

**Issue by malithj** [NERSC/pytokio#63]
Hi, first of all, thank you for this amazing tool. I tried it with python2 and works like a charm.

I was trying to setup the pytokio tool with python3 but I keep getting an error when importing. I think this is due to the fact that `iteritems ` was removed in python3. 

`>>> import tokio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/pytokio-0.10.1b1/tokio/__init__.py", line 7, in <module>
    import tokio.config
  File "/opt/pytokio-0.10.1b1/tokio/config.py", line 71, in <module>
    init_config()
  File "/opt/pytokio-0.10.1b1/tokio/config.py", line 44, in init_config
    for _key, _value in _LOADED_CONFIG.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
`

**Comment by glennklockwood** [comment]
Python 3 was not supported in v0.10, so you'll have to use the master branch if you need Python 3 support.  v0.11 will hopefully be released before the end of the year with full support.
