### ISSUE TITLE
summarize_job crashes in retrieve_ost_data

### ISSUE THREAD

**Issue by glennklockwood** [NERSC/pytokio#78]
There's an unhandled exception being triggered by the new get_fullness_hdf5 code path:

```
Traceback (most recent call last):
  File "/global/u2/g/glock/src/git/tokio-abcutils/pytokio/bin/summarize_job.py", line 6, in <module>
    main()
  File "/global/homes/g/glock/src/git/pytokio/tokio/cli/summarize_job.py", line 670, in main
    results = retrieve_ost_data(results, args.ost, args.ost_fullness, args.ost_map)
  File "/global/homes/g/glock/src/git/pytokio/tokio/cli/summarize_job.py", line 540, in retrieve_ost_data
    cache_file=ost_fullness)
  File "/global/homes/g/glock/src/git/pytokio/tokio/tools/lfsstatus.py", line 39, in get_fullness
    fullness = get_fullness_hdf5(file_system, datetime_target)
  File "/global/homes/g/glock/src/git/pytokio/tokio/tools/lfsstatus.py", line 280, in get_fullness_hdf5
    summarized_data = _summarize_fullness(results)
  File "/global/homes/g/glock/src/git/pytokio/tokio/tools/lfsstatus.py", line 344, in _summarize_fullness
    results['ost_least_full_pct'] = 100.0 * ost_data['used_kib'] / ost_data['total_kib']
ZeroDivisionError: float division by zero
```

**Comment by glennklockwood** [comment]
This was fixed by 023471b and a87e7be
